# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\IBProjects\ArmorPorts\LabComparison\IBConverter\gui\IBConverter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 834)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.taskList = QtWidgets.QListWidget(self.centralwidget)
        self.taskList.setObjectName("taskList")
        self.verticalLayout_12.addWidget(self.taskList)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addFolder = QtWidgets.QPushButton(self.centralwidget)
        self.addFolder.setObjectName("addFolder")
        self.verticalLayout_2.addWidget(self.addFolder)
        self.addFile = QtWidgets.QPushButton(self.centralwidget)
        self.addFile.setObjectName("addFile")
        self.verticalLayout_2.addWidget(self.addFile)
        self.removeFile = QtWidgets.QPushButton(self.centralwidget)
        self.removeFile.setObjectName("removeFile")
        self.verticalLayout_2.addWidget(self.removeFile)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalGroupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.verticalGroupBox_6.setObjectName("verticalGroupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalGroupBox_6)
        self.verticalLayout_7.setContentsMargins(-1, 2, -1, 6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.verticalGroupBox_6)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.convertMrl3 = QtWidgets.QCheckBox(self.verticalGroupBox_6)
        self.convertMrl3.setChecked(True)
        self.convertMrl3.setObjectName("convertMrl3")
        self.verticalLayout_6.addWidget(self.convertMrl3)
        self.convertCTC = QtWidgets.QCheckBox(self.verticalGroupBox_6)
        self.convertCTC.setChecked(True)
        self.convertCTC.setObjectName("convertCTC")
        self.verticalLayout_6.addWidget(self.convertCTC)
        self.convertCCL = QtWidgets.QCheckBox(self.verticalGroupBox_6)
        self.convertCCL.setChecked(True)
        self.convertCCL.setObjectName("convertCCL")
        self.verticalLayout_6.addWidget(self.convertCCL)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.convertEVBD = QtWidgets.QCheckBox(self.verticalGroupBox_6)
        self.convertEVBD.setChecked(True)
        self.convertEVBD.setObjectName("convertEVBD")
        self.verticalLayout_3.addWidget(self.convertEVBD)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalGroupBox_6)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.bodyDefault = QtWidgets.QRadioButton(self.groupBox_2)
        self.bodyDefault.setChecked(True)
        self.bodyDefault.setObjectName("bodyDefault")
        self.verticalLayout_10.addWidget(self.bodyDefault)
        self.bodySearch = QtWidgets.QRadioButton(self.groupBox_2)
        self.bodySearch.setObjectName("bodySearch")
        self.verticalLayout_10.addWidget(self.bodySearch)
        self.bodyCase = QtWidgets.QRadioButton(self.groupBox_2)
        self.bodyCase.setObjectName("bodyCase")
        self.verticalLayout_10.addWidget(self.bodyCase)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.convertEVHL = QtWidgets.QCheckBox(self.verticalGroupBox_6)
        self.convertEVHL.setChecked(True)
        self.convertEVHL.setObjectName("convertEVHL")
        self.verticalLayout_5.addWidget(self.convertEVHL)
        self.groupBox = QtWidgets.QGroupBox(self.verticalGroupBox_6)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.headHollow = QtWidgets.QRadioButton(self.groupBox)
        self.headHollow.setObjectName("headHollow")
        self.verticalLayout_9.addWidget(self.headHollow)
        self.headHair = QtWidgets.QRadioButton(self.groupBox)
        self.headHair.setObjectName("headHair")
        self.verticalLayout_9.addWidget(self.headHair)
        self.headSearch = QtWidgets.QRadioButton(self.groupBox)
        self.headSearch.setObjectName("headSearch")
        self.verticalLayout_9.addWidget(self.headSearch)
        self.headCase = QtWidgets.QRadioButton(self.groupBox)
        self.headCase.setCheckable(True)
        self.headCase.setChecked(True)
        self.headCase.setObjectName("headCase")
        self.verticalLayout_9.addWidget(self.headCase)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.convertEVWP = QtWidgets.QCheckBox(self.verticalGroupBox_6)
        self.convertEVWP.setChecked(True)
        self.convertEVWP.setObjectName("convertEVWP")
        self.verticalLayout_4.addWidget(self.convertEVWP)
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalGroupBox_6)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.weaponDefault = QtWidgets.QRadioButton(self.groupBox_3)
        self.weaponDefault.setChecked(True)
        self.weaponDefault.setObjectName("weaponDefault")
        self.verticalLayout_11.addWidget(self.weaponDefault)
        self.weaponSearch = QtWidgets.QRadioButton(self.groupBox_3)
        self.weaponSearch.setObjectName("weaponSearch")
        self.verticalLayout_11.addWidget(self.weaponSearch)
        self.weaponCase = QtWidgets.QRadioButton(self.groupBox_3)
        self.weaponCase.setObjectName("weaponCase")
        self.verticalLayout_11.addWidget(self.weaponCase)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.horizontalLayout.addWidget(self.verticalGroupBox_6)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_14.addWidget(self.label_2)
        self.Log = QtWidgets.QTextBrowser(self.centralwidget)
        self.Log.setObjectName("Log")
        self.verticalLayout_14.addWidget(self.Log)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.debug = QtWidgets.QCheckBox(self.centralwidget)
        self.debug.setObjectName("debug")
        self.horizontalLayout_3.addWidget(self.debug)
        self.convertButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertButton.setObjectName("convertButton")
        self.horizontalLayout_3.addWidget(self.convertButton)
        self.verticalLayout_14.addLayout(self.horizontalLayout_3)
        self.verticalLayout_13.addLayout(self.verticalLayout_14)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setWordWrap(True)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_13.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.verticalLayout_13)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Files to Convert"))
        self.addFolder.setText(_translate("MainWindow", "Add Folder"))
        self.addFile.setText(_translate("MainWindow", "Add File"))
        self.removeFile.setText(_translate("MainWindow", "Remove Folder/ Files"))
        self.label.setText(_translate("MainWindow", "Formats to Convert"))
        self.convertMrl3.setText(_translate("MainWindow", "MRL3"))
        self.convertCTC.setText(_translate("MainWindow", "CTC"))
        self.convertCCL.setText(_translate("MainWindow", "CCL"))
        self.convertEVBD.setText(_translate("MainWindow", "EVBD"))
        self.bodyDefault.setText(_translate("MainWindow", "Default Body Position"))
        self.bodySearch.setText(_translate("MainWindow", "Search for Best Match"))
        self.bodyCase.setText(_translate("MainWindow", "Prompt me for each case"))
        self.convertEVHL.setText(_translate("MainWindow", "EVHL"))
        self.headHollow.setText(_translate("MainWindow", "Hollow Head (No Player Head)"))
        self.headHair.setText(_translate("MainWindow", "Full Hair (Player Head Intact)"))
        self.headSearch.setText(_translate("MainWindow", "Search for Best Match"))
        self.headCase.setText(_translate("MainWindow", "Prompt me for each case"))
        self.convertEVWP.setText(_translate("MainWindow", "EVWP"))
        self.weaponDefault.setText(_translate("MainWindow", "Default Position"))
        self.weaponSearch.setText(_translate("MainWindow", "Search for Best Match"))
        self.weaponCase.setText(_translate("MainWindow", "Prompt me for each case"))
        self.label_2.setText(_translate("MainWindow", "Log"))
        self.debug.setText(_translate("MainWindow", "Enable Debugging Mode"))
        self.convertButton.setText(_translate("MainWindow", "Convert"))
        self.label_4.setText(_translate("MainWindow", "Many thanks to CrazyT for his dissasembly tools for the Shader files, 冰块冰块冰 Ice for his work on the CTC Structural changes, Statyk for his work on the CTC structural changes and testing, Silvris for his help with the research of EVXX structural differences and miscellaneous research tasks, asdasdasdasd, Nack, ๓ٱɼคɭٱร and LyraVeil for testing. Application code and mrl3, evhl, evbd, evwp research by Asterisk.\n"
"\n"
"The author can be found on the Modding Discord: https://discord.gg/gJwMdhK \n"
"And can be supported on Patreon: https://www.patreon.com/user?u=21034864"))

